# Render Blueprint: deploys the Laravel backend from the mbektemi-api subdirectory using Docker
# Docs: https://render.com/docs/blueprint-spec

services:
  - type: web
    name: mbektemi-api
    env: docker
    rootDir: mbektemi-api
    plan: starter
    autoDeploy: true
    healthCheckPath: /up
    # Render injects PORT (default 10000). Our Dockerfile binds to $PORT.

    envVars:
      # General
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_TIMEZONE
        value: Africa/Dakar

      # URL and Sanctum/CORS (replace with your actual domains)
      - key: APP_URL
        value: https://api.mbektemi.sn
      - key: SESSION_DOMAIN
        value: mbektemi.sn
      - key: SESSION_SECURE_COOKIE
        value: true
      - key: SANCTUM_STATEFUL_DOMAINS
        value: mbektemi.sn,www.mbektemi.sn
      - key: FRONTEND_URL
        value: https://mbektemi.sn
      - key: CORS_ALLOWED_ORIGINS
        value: https://mbektemi.sn,https://www.mbektemi.sn

      # Admin emails (comma-separated)
      - key: ADMIN_EMAILS
        value: admin@mbektemi.sn,gadjicheikh15@gmail.com

      # Database (fill with your managed DB credentials on Render)
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_HOST
        sync: false   # set in Render dashboard or via "render env set"
      - key: DB_PORT
        value: "5432"
      - key: DB_DATABASE
        sync: false
      - key: DB_USERNAME
        sync: false
      - key: DB_PASSWORD
        sync: false
      # - key: DB_SCHEMA
      #   value: public

      # Cache/Queue (simple defaults)
      - key: CACHE_DRIVER
        value: file
      - key: QUEUE_CONNECTION
        value: sync
      - key: FILESYSTEM_DISK
        value: local

      # Mail (optional; set only if you use SMTP)
      # - key: MAIL_MAILER
      #   value: smtp
      # - key: MAIL_HOST
      #   sync: false
      # - key: MAIL_PORT
      #   value: "587"
      # - key: MAIL_USERNAME
      #   sync: false
      # - key: MAIL_PASSWORD
      #   sync: false
      # - key: MAIL_ENCRYPTION
      #   value: tls
      # - key: MAIL_FROM_ADDRESS
      #   value: no-reply@mbektemi.sn
      # - key: MAIL_FROM_NAME
      #   value: MbekteMi

# Usage:
# 1) Commit this file, push to GitHub.
# 2) In Render: New -> Blueprint -> select this repository.
# 3) After the first deploy, set DB_* values (DB_HOST, DB_DATABASE, DB_USERNAME, DB_PASSWORD) in the Render dashboard if not set.