#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

echo "Running pre-commit checks..."
if command -v pnpm >/dev/null 2>&1; then
  pnpm lint && pnpm type-check
else
  npm run lint && npm run type-check
fi